### ISSUE TITLE
IOS BUILD FAILED Cordova/NSData+Base64.h' file not found

### ISSUE THREAD

**Issue by Cultrarius** [DisyInformationssysteme/Cordova-spatialite-storage#1]
> Hi,
I am new to github so I am not sure if this is the right place to write but I don't see way to create issue.
I am writing cordova map application which is heavily using cordova-spatial-storage plugin. On Android works like a charm but have problem on IOS. It doesn't compile and I get error mentioned in title.
I have
macOS Sierra 10.12.13
Xcode 8.2.1
cordova-ios 4.1.1
cordova-cli 6.4.0
and trying to compile it from Visual Studio 2015 installed on win10 machine. As I did some searches bug is caused by some changes in cordova and many plugins face it, including main branch of sqlite plugin.
Is there a chance to have a upgrade this plugin to latest cordova ?

**Comment by Cultrarius** [comment]
Hey @LukeeK,
we are currently using cordova version 5.4.1, so we do not face this problem.

The cause is apparently not the cordova version, but the version of the ios module: https://github.com/apache/cordova-ios/blob/master/guides/API%20changes%20in%204.0.md#nsdatabase64h-removed

I do not know if this can be easily fixed, maybe it requires a separate branch.

**Comment by KimberleeDArmstrong** [comment]
I looked through the bugs on the parent sqlite plugin as it seems to be more active and kept up to date. I found a solution there.  You can replace SQLitePlugin.m file in plugins/src/ios with the SQLItePlugin.m file text below...

/*
 * Copyright (C) 2012-2015 Chris Brody
 * Copyright (C) 2011 Davide Bertola
 *
 * This library is available under the terms of the MIT License (2008).
 * See http://opensource.org/licenses/alphabetical for full text.
 */

#import "SQLitePlugin.h"

#import "sqlite3.h"
#import "spatialite.h"

#include <regex.h>

#import <Cordova/NSData+Base64.h>

static void sqlite_regexp(sqlite3_context* context, int argc, sqlite3_value** values) {
    if ( argc < 2 ) {
        sqlite3_result_error(context, "SQL function regexp() called with missing arguments.", -1);
        return;
    }

    char* reg = (char*)sqlite3_value_text(values[0]);
    char* text = (char*)sqlite3_value_text(values[1]);

    if ( argc != 2 || reg == 0 || text == 0) {
        sqlite3_result_error(context, "SQL function regexp() called with invalid arguments.", -1);
        return;
    }

    int ret;
    regex_t regex;

    ret = regcomp(&regex, reg, REG_EXTENDED | REG_NOSUB);
    if ( ret != 0 ) {
        sqlite3_result_error(context, "error compiling regular expression", -1);
        return;
    }

    ret = regexec(&regex, text , 0, NULL, 0);
    regfree(&regex);

    sqlite3_result_int(context, (ret != REG_NOMATCH));
}


@implementation SQLitePlugin

@synthesize openDBs;
@synthesize openConnections;
@synthesize appDBPaths;

-(void)pluginInitialize
{
    NSLog(@"Initializing SQLitePlugin");

    {
        openDBs = [NSMutableDictionary dictionaryWithCapacity:0];
        openConnections = [NSMutableDictionary dictionaryWithCapacity:0];
        appDBPaths = [NSMutableDictionary dictionaryWithCapacity:0];
#if !__has_feature(objc_arc)
        [openDBs retain];
        [appDBPaths retain];
#endif

        NSString *docs = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex: 0];
        NSLog(@"Detected docs path: %@", docs);
        [appDBPaths setObject: docs forKey:@"docs"];

        NSString *libs = [NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES) objectAtIndex: 0];
        NSLog(@"Detected Library path: %@", libs);
        [appDBPaths setObject: libs forKey:@"libs"];

        NSString *nosync = [libs stringByAppendingPathComponent:@"LocalDatabase"];
        NSError *err;
        if ([[NSFileManager defaultManager] fileExistsAtPath: nosync])
        {
            NSLog(@"no cloud sync at path: %@", nosync);
            [appDBPaths setObject: nosync forKey:@"nosync"];
        }
        else
        {
            if ([[NSFileManager defaultManager] createDirectoryAtPath: nosync withIntermediateDirectories:NO attributes: nil error:&err])
            {
                NSURL *nosyncURL = [ NSURL fileURLWithPath: nosync];
                if (![nosyncURL setResourceValue: [NSNumber numberWithBool: YES] forKey: NSURLIsExcludedFromBackupKey error: &err])
                {
                    NSLog(@"IGNORED: error setting nobackup flag in LocalDatabase directory: %@", err);
                }
                NSLog(@"no cloud sync at path: %@", nosync);
                [appDBPaths setObject: nosync forKey:@"nosync"];
            }
            else
            {
                // fallback:
                NSLog(@"WARNING: error adding LocalDatabase directory: %@", err);
                [appDBPaths setObject: libs forKey:@"nosync"];
            }
        }
    }
}

-(void)open: (CDVInvokedUrlCommand*)command
{
    CDVPluginResult* pluginResult = nil;
    NSMutableDictionary *options = [command.arguments objectAtIndex:0];

    NSString *dbfilename = [options objectForKey:@"name"];

    if (dbfilename == NULL) {
        NSLog(@"No db specified for open");
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"You must specify database name"];
    }
    else {
        NSValue *dbPointer = [openDBs objectForKey:dbfilename];

        if (dbPointer != NULL) {
            NSLog(@"Reusing existing database connection for db name %@", dbfilename);
            pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"Database opened"];
        } else {
            NSURL *url = [NSURL URLWithString:dbfilename];
            NSString *absoluteFile = [url path];
            
            const char *name = [absoluteFile UTF8String];
            sqlite3 *db;

            NSLog(@"open full db path: %@", absoluteFile);
            /* Option to create from resource (pre-populated) if db does not exist: */
            if (![[NSFileManager defaultManager] fileExistsAtPath:absoluteFile]) {
				NSLog(@"Error! Unable to find database!");
                return;
            }

            if (sqlite3_open(name, &db) != SQLITE_OK) {
                pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"Unable to open DB"];
                return;
            } else {
                sqlite3_create_function(db, "regexp", 2, SQLITE_ANY, NULL, &sqlite_regexp, NULL, NULL);

                // for SQLCipher version:
                // NSString *dbkey = [options objectForKey:@"key"];
                // const char *key = NULL;
                // if (dbkey != NULL) key = [dbkey UTF8String];
                // if (key != NULL) sqlite3_key(db, key, strlen(key));

                // Attempt to read the SQLite master table [to support SQLCipher version]:
                if(sqlite3_exec(db, (const char*)"SELECT count(*) FROM sqlite_master;", NULL, NULL, NULL) == SQLITE_OK) {
                    dbPointer = [NSValue valueWithPointer:db];
                    [openDBs setObject: dbPointer forKey: dbfilename];
                    pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"Database opened"];
                } else {
                    pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"Unable to open DB with key"];
                    // XXX TODO: close the db handle & [perhaps] remove from openDBs!!
                }
            }
            
            // initialize spatialite
            void* cache = spatialite_alloc_connection ();
            spatialite_init_ex (db, cache, 1);
            NSValue *cachePointer = [NSValue valueWithPointer:cache];
            [openConnections setObject: cachePointer forKey: dbPointer];
        }
    }

    if (sqlite3_threadsafe()) {
        NSLog(@"Good news: SQLite is thread safe!");
    }
    else {
        NSLog(@"Warning: SQLite is not thread safe.");
    }

    [self.commandDelegate sendPluginResult:pluginResult callbackId: command.callbackId];

    // NSLog(@"open cb finished ok");
}


-(void)createFromResource:(NSString *)dbfile withDbname:(NSString *)dbname {
    NSString *bundleRoot = [[NSBundle mainBundle] resourcePath];
    NSString *www = [bundleRoot stringByAppendingPathComponent:@"www"];
    NSString *prepopulatedDb = [www stringByAppendingPathComponent: dbfile];
    // NSLog(@"Look for prepopulated DB at: %@", prepopulatedDb);

    if ([[NSFileManager defaultManager] fileExistsAtPath:prepopulatedDb]) {
        NSLog(@"Found prepopulated DB: %@", prepopulatedDb);
        NSError *error;
        BOOL success = [[NSFileManager defaultManager] copyItemAtPath:prepopulatedDb toPath:dbname error:&error];

        if(success)
            NSLog(@"Copied prepopulated DB content to: %@", dbname);
        else
            NSLog(@"Unable to copy DB file: %@", [error localizedDescription]);
    }
}


-(void) close: (CDVInvokedUrlCommand*)command
{
    CDVPluginResult* pluginResult = nil;
    NSMutableDictionary *options = [command.arguments objectAtIndex:0];

    NSString *dbFileName = [options objectForKey:@"path"];

    if (dbFileName == NULL) {
        // Should not happen:
        NSLog(@"No db name specified for close");
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"You must specify database path"];
    } else {
        NSValue *val = [openDBs objectForKey:dbFileName];
        sqlite3 *db = [val pointerValue];

        if (db == NULL) {
            // Should not happen:
            NSLog(@"close: db name was not open: %@", dbFileName);
            pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"Specified db was not open"];
        }
        else {
            NSLog(@"close db name: %@", dbFileName);
            sqlite3_close (db);
            [openDBs removeObjectForKey:dbFileName];
            
            // clean up spatialite
            NSValue *cacheVal = [openConnections objectForKey:val];
            void *cache = [cacheVal pointerValue];
            spatialite_cleanup_ex(cache);
            [openConnections removeObjectForKey:val];
            
            pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"DB closed"];
        }
    }

    [self.commandDelegate sendPluginResult:pluginResult callbackId: command.callbackId];
}

-(void) delete: (CDVInvokedUrlCommand*)command
{
    CDVPluginResult* pluginResult = nil;
    NSMutableDictionary *options = [command.arguments objectAtIndex:0];

    NSString *dbFileName = [options objectForKey:@"path"];

    if (dbFileName==NULL) {
        // Should not happen:
        NSLog(@"No db name specified for delete");
        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"You must specify database path"];
    } else {
        if ([[NSFileManager defaultManager]fileExistsAtPath:dbFileName]) {
            NSLog(@"delete full db path: %@", dbFileName);
            [[NSFileManager defaultManager]removeItemAtPath:dbFileName error:nil];
            [openDBs removeObjectForKey:dbFileName];
            pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"DB deleted"];
        } else {
            NSLog(@"delete: db was not found: %@", dbFileName);
            pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"The database does not exist on that path"];
        }
    }
    [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
}


-(void) backgroundExecuteSqlBatch: (CDVInvokedUrlCommand*)command
{
    [self.commandDelegate runInBackground:^{
        [self executeSqlBatch: command];
    }];
}

-(void) executeSqlBatch: (CDVInvokedUrlCommand*)command
{
    NSMutableDictionary *options = [command.arguments objectAtIndex:0];
    NSMutableArray *results = [NSMutableArray arrayWithCapacity:0];
    NSMutableDictionary *dbargs = [options objectForKey:@"dbargs"];
    NSMutableArray *executes = [options objectForKey:@"executes"];

    CDVPluginResult* pluginResult;

    @synchronized(self) {
        for (NSMutableDictionary *dict in executes) {
            CDVPluginResult *result = [self executeSqlWithDict:dict andArgs:dbargs];
            if ([result.status intValue] == CDVCommandStatus_ERROR) {
                /* add error with result.message: */
                NSMutableDictionary *r = [NSMutableDictionary dictionaryWithCapacity:0];
                [r setObject:[dict objectForKey:@"qid"] forKey:@"qid"];
                [r setObject:@"error" forKey:@"type"];
                [r setObject:result.message forKey:@"error"];
                [r setObject:result.message forKey:@"result"];
                [results addObject: r];
            } else {
                /* add result with result.message: */
                NSMutableDictionary *r = [NSMutableDictionary dictionaryWithCapacity:0];
                [r setObject:[dict objectForKey:@"qid"] forKey:@"qid"];
                [r setObject:@"success" forKey:@"type"];
                [r setObject:result.message forKey:@"result"];
                [results addObject: r];
            }
        }

        pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsArray:results];
    }

    [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
}

-(void) backgroundExecuteSql: (CDVInvokedUrlCommand*)command
{
    [self.commandDelegate runInBackground:^{
        [self executeSql:command];
    }];
}

-(void) executeSql: (CDVInvokedUrlCommand*)command
{
    NSMutableDictionary *options = [command.arguments objectAtIndex:0];
    NSMutableDictionary *dbargs = [options objectForKey:@"dbargs"];
    NSMutableDictionary *ex = [options objectForKey:@"ex"];

    CDVPluginResult* pluginResult;
    @synchronized (self) {
        pluginResult = [self executeSqlWithDict: ex andArgs: dbargs];
    }
    [self.commandDelegate sendPluginResult:pluginResult callbackId:command.callbackId];
}

-(CDVPluginResult*) executeSqlWithDict: (NSMutableDictionary*)options andArgs: (NSMutableDictionary*)dbargs
{
    NSString *dbFileName = [dbargs objectForKey:@"dbname"];
    if (dbFileName == NULL) {
        return [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"You must specify database path"];
    }

    NSMutableArray *params = [options objectForKey:@"params"]; // optional

    NSValue *dbPointer = [openDBs objectForKey:dbFileName];
    if (dbPointer == NULL) {
        return [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"No such database, you must open it first"];
    }
    sqlite3 *db = [dbPointer pointerValue];

    NSString *sql = [options objectForKey:@"sql"];
    if (sql == NULL) {
        return [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"You must specify a sql query to execute"];
    }

    const char *sql_stmt = [sql UTF8String];
    NSDictionary *error = nil;
    sqlite3_stmt *statement;
    int result, i, column_type, count;
    int previousRowsAffected, nowRowsAffected, diffRowsAffected;
    long long previousInsertId, nowInsertId;
    BOOL keepGoing = YES;
    BOOL hasInsertId;
    NSMutableDictionary *resultSet = [NSMutableDictionary dictionaryWithCapacity:0];
    NSMutableArray *resultRows = [NSMutableArray arrayWithCapacity:0];
    NSMutableDictionary *entry;
    NSObject *columnValue;
    NSString *columnName;
    NSObject *insertId;
    NSObject *rowsAffected;

    hasInsertId = NO;
    previousRowsAffected = sqlite3_total_changes(db);
    previousInsertId = sqlite3_last_insert_rowid(db);

    if (sqlite3_prepare_v2(db, sql_stmt, -1, &statement, NULL) != SQLITE_OK) {
        error = [SQLitePlugin captureSQLiteErrorFromDb:db];
        keepGoing = NO;
    } else if (params != NULL) {
        for (int b = 0; b < params.count; b++) {
            [self bindStatement:statement withArg:[params objectAtIndex:b] atIndex:(b+1)];
        }
    }

    while (keepGoing) {
        result = sqlite3_step (statement);
        switch (result) {

            case SQLITE_ROW:
                i = 0;
                entry = [NSMutableDictionary dictionaryWithCapacity:0];
                count = sqlite3_column_count(statement);

                while (i < count) {
                    columnValue = nil;
                    columnName = [NSString stringWithFormat:@"%s", sqlite3_column_name(statement, i)];

                    column_type = sqlite3_column_type(statement, i);
                    switch (column_type) {
                        case SQLITE_INTEGER:
                            columnValue = [NSNumber numberWithDouble: sqlite3_column_double(statement, i)];
                            break;
                        case SQLITE_TEXT:
                            columnValue = [[NSString alloc] initWithBytes:(char *)sqlite3_column_text(statement, i)
                                                                   length:sqlite3_column_bytes(statement, i)
                                                                 encoding:NSUTF8StringEncoding];
#if !__has_feature(objc_arc)
                            [columnValue autorelease];
#endif
                            break;
                        case SQLITE_BLOB:
                            columnValue = [SQLitePlugin getBlobAsBase64String: sqlite3_column_blob(statement, i)
                                                        withLength: sqlite3_column_bytes(statement, i)];
#ifdef INCLUDE_SQL_BLOB_BINDING // TBD subjet to change:
                            columnValue = [@"sqlblob:;base64," stringByAppendingString:columnValue];
#endif
                            break;
                        case SQLITE_FLOAT:
                            columnValue = [NSNumber numberWithDouble: sqlite3_column_double(statement, i)];
                            break;
                        case SQLITE_NULL:
                            columnValue = [NSNull null];
                            break;
                    }

                    if (columnValue) {
                        [entry setObject:columnValue forKey:columnName];
                    }

                    i++;
                }
                [resultRows addObject:entry];
                break;

            case SQLITE_DONE:
                nowRowsAffected = sqlite3_total_changes(db);
                diffRowsAffected = nowRowsAffected - previousRowsAffected;
                rowsAffected = [NSNumber numberWithInt:diffRowsAffected];
                nowInsertId = sqlite3_last_insert_rowid(db);
                if (nowRowsAffected > 0 && nowInsertId != 0) {
                    hasInsertId = YES;
                    insertId = [NSNumber numberWithLongLong:sqlite3_last_insert_rowid(db)];
                }
                keepGoing = NO;
                break;

            default:
                error = [SQLitePlugin captureSQLiteErrorFromDb:db];
                keepGoing = NO;
        }
    }

    sqlite3_finalize (statement);

    if (error) {
        return [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsDictionary:error];
    }

    [resultSet setObject:resultRows forKey:@"rows"];
    [resultSet setObject:rowsAffected forKey:@"rowsAffected"];
    if (hasInsertId) {
        [resultSet setObject:insertId forKey:@"insertId"];
    }
    return [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsDictionary:resultSet];
}

-(void)bindStatement:(sqlite3_stmt *)statement withArg:(NSObject *)arg atIndex:(NSUInteger)argIndex
{
    if ([arg isEqual:[NSNull null]]) {
        sqlite3_bind_null(statement, argIndex);
    } else if ([arg isKindOfClass:[NSNumber class]]) {
        NSNumber *numberArg = (NSNumber *)arg;
        const char *numberType = [numberArg objCType];
        if (strcmp(numberType, @encode(int)) == 0) {
            sqlite3_bind_int(statement, argIndex, [numberArg integerValue]);
        } else if (strcmp(numberType, @encode(long long int)) == 0) {
            sqlite3_bind_int64(statement, argIndex, [numberArg longLongValue]);
        } else if (strcmp(numberType, @encode(double)) == 0) {
            sqlite3_bind_double(statement, argIndex, [numberArg doubleValue]);
        } else {
            sqlite3_bind_text(statement, argIndex, [[arg description] UTF8String], -1, SQLITE_TRANSIENT);
        }
    } else { // NSString
        NSString *stringArg;

        if ([arg isKindOfClass:[NSString class]]) {
            stringArg = (NSString *)arg;
        } else {
            stringArg = [arg description]; // convert to text
        }

#ifdef INCLUDE_SQL_BLOB_BINDING // TBD subjet to change:
        // If the string is a sqlblob URI then decode it and store the binary directly.
        //
        // A sqlblob URI is formatted similar to a data URI which makes it easy to convert:
        //   sqlblob:[<mime type>][;charset=<charset>][;base64],<encoded data>
        //
        // The reason the `sqlblob` prefix is used instead of `data` is because
        // applications may want to use data URI strings directly, so the
        // `sqlblob` prefix disambiguates the desired behavior.
        if ([stringArg hasPrefix:@"sqlblob:"]) {
            // convert to data URI, decode, store as blob
            stringArg = [stringArg stringByReplacingCharactersInRange:NSMakeRange(0,7) withString:@"data"];
            NSData *data = [NSData dataWithContentsOfURL: [NSURL URLWithString:stringArg]];
            sqlite3_bind_blob(statement, argIndex, data.bytes, data.length, SQLITE_TRANSIENT);
        }
        else
#endif
        {
            NSData *data = [stringArg dataUsingEncoding:NSUTF8StringEncoding];
            sqlite3_bind_text(statement, argIndex, data.bytes, data.length, SQLITE_TRANSIENT);
        }
    }
}

-(void)dealloc
{
    int i;
    NSArray *keys = [openDBs allKeys];
    NSValue *pointer;
    NSString *key;
    sqlite3 *db;

    /* close db the user forgot */
    for (i=0; i<[keys count]; i++) {
        key = [keys objectAtIndex:i];
        pointer = [openDBs objectForKey:key];
        db = [pointer pointerValue];
        sqlite3_close (db);
    }

#if !__has_feature(objc_arc)
    [openDBs release];
    [appDBPaths release];
    [super dealloc];
#endif
}

+(NSDictionary *)captureSQLiteErrorFromDb:(struct sqlite3 *)db
{
    int code = sqlite3_errcode(db);
    int webSQLCode = [SQLitePlugin mapSQLiteErrorCode:code];
#if INCLUDE_SQLITE_ERROR_INFO
    int extendedCode = sqlite3_extended_errcode(db);
#endif
    const char *message = sqlite3_errmsg(db);

    NSMutableDictionary *error = [NSMutableDictionary dictionaryWithCapacity:4];

    [error setObject:[NSNumber numberWithInt:webSQLCode] forKey:@"code"];
    [error setObject:[NSString stringWithUTF8String:message] forKey:@"message"];

#if INCLUDE_SQLITE_ERROR_INFO
    [error setObject:[NSNumber numberWithInt:code] forKey:@"sqliteCode"];
    [error setObject:[NSNumber numberWithInt:extendedCode] forKey:@"sqliteExtendedCode"];
    [error setObject:[NSString stringWithUTF8String:message] forKey:@"sqliteMessage"];
#endif

    return error;
}

+(int)mapSQLiteErrorCode:(int)code
{
    // map the sqlite error code to
    // the websql error code
    switch(code) {
        case SQLITE_ERROR:
            return SYNTAX_ERR;
        case SQLITE_FULL:
            return QUOTA_ERR;
        case SQLITE_CONSTRAINT:
            return CONSTRAINT_ERR;
        default:
            return UNKNOWN_ERR;
    }
}

+(NSString*)getBlobAsBase64String:(const char*)blob_chars
                       withLength:(int)blob_length
{
    size_t outputLength = 0;
    char* outputBuffer = CDVNewBase64Encode(blob_chars, blob_length, true, &outputLength);

    NSString* result = [[NSString alloc] initWithBytesNoCopy:outputBuffer
                                                      length:outputLength
                                                    encoding:NSASCIIStringEncoding
                                                freeWhenDone:YES];
#if !__has_feature(objc_arc)
    [result autorelease];
#endif

    return result;
}

@end /* vim: set expandtab : */

**Comment by KimberleeDArmstrong** [comment]
I looked through the bugs on the parent sqlite plugin as it seems to be more active and kept up to date. I found a solution there.  You can replace SQLitePlugin.m file in plugins/src/ios with the SQLItePlugin.txt file I attached just rename the file to SQLitePlugin.m  Git hub doesn't recognize the .m file extension.
[SQLitePlugin.m.txt](https://github.com/DisyInformationssysteme/Cordova-spatialite-storage/files/767089/SQLitePlugin.m.txt)

**Comment by Cultrarius** [comment]
Thanks @KimberleeDArmstrong but the file you attached did not have the fix included, maybe you linked the wrong file? Your file still includes the problematic header `#import <Cordova/NSData+Base64.h>`.

I merged the missing commits from upstream, so it should work now. I tested it for cordova-ios version  3.8.0, but not with the problematic version from @LukeeK. When someone with a version > 4.0.0 could test it now and report back that would be great!
(you probably have to remove and reinstall the plugin via cordova for it to work)

The fix from upstream basically disables the SQLite blob storage; if you need the feature to work you have to `#define` the `READ_BLOB_AS_BASE64` macro.

**Comment by LukeeK** [comment]
Hi,
thanks for quick response. I will check it on monday when I get to work, where I have my Mac. 
Btw, You are right not cordova itself but cordova-ios.

**Comment by LukeeK** [comment]
Hi,
I tried to build default apache cordova project from Visual Studio with newest spatialite plugin version but got some linker errors:
Undefined symbols for architecture x86_64:
    "_uncompress", referenced from:
        _gaiaXmlBlobCompression in libspatialite.a(gg_xml.o)
        _gaiaXmlTextFromBlob in libspatialite.a(gg_xml.o)
        _gaiaXmlFromBlob in libspatialite.a(gg_xml.o)
        _gaiaXmlBlobSetFileId in libspatialite.a(gg_xml.o)
        _gaiaXmlBlobSetParentId in libspatialite.a(gg_xml.o)
        _gaiaXmlBlobAddFileId in libspatialite.a(gg_xml.o)
        _gaiaXmlBlobAddParentId in libspatialite.a(gg_xml.o)
        ...
    "_compressBound", referenced from:
        _gaiaXmlToBlob in libspatialite.a(gg_xml.o)
        _gaiaXmlBlobCompression in libspatialite.a(gg_xml.o)
    "_compress", referenced from:
        _gaiaXmlToBlob in libspatialite.a(gg_xml.o)
        _gaiaXmlBlobCompression in libspatialite.a(gg_xml.o)
    "_crc32", referenced from:
        _evalGeosCache in libspatialite.a(gg_relations.o)
        _gaiaXmlToBlob in libspatialite.a(gg_xml.o)
        _gaiaXmlBlobCompression in libspatialite.a(gg_xml.o)
        _gaiaIsValidXmlBlob in libspatialite.a(gg_xml.o)
        _is_valid_legacy_xml_blob in libspatialite.a(gg_xml.o)
  ld: symbol(s) not found for architecture x86_64
clang : error : linker command failed with exit code 1 (use -v to see invocation)

**Comment by Cultrarius** [comment]
@LukeeK thank you for the test.
Are you building your iOS project from Visual Studio? Maybe try to use XCode, I think it has better support.

You might also try to add libz.dylib as lib to your project: http://stackoverflow.com/a/8768277/2092777
Please open another ticket if this problem persists, so it does not get mixed up with this one.

**Comment by LukeeK** [comment]
@Cultrarius, thanks for info.
I've already built and run my app with old version of spatialite plugin (before last commits, including Cordova/NSData+Base64.h' file not found bug) directly on mac with Xcode. I had to include NSData+Base64.m, NSData+Base64.h files add  refence to libz.1.2.8.tbd and do few more tweeks.
And of course that is the option, however I was hoping to have it run from vstudio as I am more familiar with it and it gives more options to debug (at least from my perspective).

**Comment by Cultrarius** [comment]
@LukeeK we only support XCode for iOS projects, but we are happy to accept a pull request if you get it to work with VS. Maybe check out the plugin.xml: under `<platform name="ios">` there are several entries such as `<framework src="libiconv.dylib" />`. Try to add the `libz.dylib`, `libz.1.2.8.tbd`, `libz.tbd` (or whatever its name now is) as a framework before installing the plugin.

**Comment by LukeeK** [comment]
@Cultrarius ,thanks I will check it. Btw is there a way to debug cordova app run in xcode on mac in real time (except  using Safari)?

**Comment by Cultrarius** [comment]
@LukeeK You can use XCode to debug the native parts (e.g. the spatialite lib), whereas Safari is used to debug the JavaScript parts of cordova. They go hand in hand ;)
I do not know of any alternatives to these two.

**Comment by LukeeK** [comment]
@Cultrarius thanks for debug possibilities info and for  `<framework src="libiconv.dylib" />` tip. That made a job and I can compile, run and debug on mac my app from visual studio

**Comment by Cultrarius** [comment]
Great, thanks! I will close the issue then.
