### ISSUE TITLE
Plugin update to be compatible with Android 64 bits

### ISSUE THREAD

**Issue by Anexo** [DisyInformationssysteme/Cordova-spatialite-storage#14]
Hi all,

I saw that the last commit adds 64 bit compatibility with Android devices, adding the .so libraries to the x86_64 and arm64-v8a folders.

When I compile my code and "unzip" the apk, I see a lib folder, with only the 32 bit libraries.

Am I missing something? Do I need to tweak the plugin.xml file?

Thanks in advance.

**Comment by c-goetz** [comment]
Hi Anexo,

I just added the missing entries to the plugin.xml files.
The produced apk now contains the 64bit binaries.

Sorry for the inconvenience.

**Comment by Anexo** [comment]
This is great! Thank you so much.
