### ISSUE TITLE
Problems on create database in Android

### ISSUE THREAD

**Issue by WilliamCesarSantos** [DisyInformationssysteme/Cordova-spatialite-storage#3]
Hi, i use this plugin and SQLCipher(https://github.com/litehelpers/Cordova-sqlcipher-adapter) in Android app, but, when it's tempted create new database in app, an error occurs, description of error: java.illegalargument.exception: URI is not absolute.
Creation of the database is in this way
window.sqlitePlugin.openDatabase({name: 'database1.db', key: '123', location: 'default', androidLockWorkaround: 1},success,error); I used Promise

**Comment by Cultrarius** [comment]
Hey,
see also Issue https://github.com/DisyInformationssysteme/Cordova-spatialite-storage/issues/2, this plugin does not create new databases on its own. It can only be used to open existing databases.
Also, you should not use `name: 'database1.db'`, but always an absolute file path.

Do you use SQLCipher and our Spatialite plugin to access the same database file? Because that is not recommended and can corrupt your database.

**Comment by WilliamCesarSantos** [comment]
Hi, Cultrarius,
I had tempted use same database for Sqlcipher and Spatialite, but isn't not possible, because this problem. Removed Spatialite temporarily.
I will use two database in future, one SqlCipher and other to Spatialite, thanks for response.

**Comment by Alma9170** [comment]
> Hey,
> see also Issue #2, this plugin does not create new databases on its own. It can only be used to open existing databases.
> Also, you should not use `name: 'database1.db'`, but always an absolute file path.
> 
> Do you use SQLCipher and our Spatialite plugin to access the same database file? Because that is not recommended and can corrupt your database.

Hello,
I am using cordova-spatialite-storage version 2.0.0, and the way I use the database is like this:
try {
        var query = 'SELECT Geometry From <any-table> ';
         var args = []; 
         var querySuccess = function (results) {
             alert(results)
         }
         var queryError = function (error) {  alert(error.toString()) }
         var spatialiteURI = "file:///storage/emulated/0/Documents/DB.sqlite";
         var db = window.sqlitePlugin.openDatabase({ name: spatialiteURI });
            db.transaction(function (tx) {
                tx.executeSql(query, args, querySuccess, queryError);
            });
    }
    catch (ex) {
        alert(ex.message)
    }
But this code is not working and the plugin can't find my database file. 
I think there is something wrong with URI I am using.
thank you in advance for your help.

**Comment by Alma9170** [comment]
> Hey,
> see also Issue #2, this plugin does not create new databases on its own. It can only be used to open existing databases.
> Also, you should not use `name: 'database1.db'`, but always an absolute file path.
> 
> Do you use SQLCipher and our Spatialite plugin to access the same database file? Because that is not recommended and can corrupt your database.

Hello,
I am using cordova-spatialite-storage version 2.0.0, and the way I use the database is like this:
try {
var query = 'SELECT Geometry From <any-table>';
var args = [];
var querySuccess = function (results) {
alert(results)
}
var queryError = function (error) { alert(error.toString()) }
var spatialiteURI = "file:///storage/emulated/0/Documents/DB.sqlite";
var db = window.sqlitePlugin.openDatabase({ name: spatialiteURI });
db.transaction(function (tx) {
tx.executeSql(query, args, querySuccess, queryError);
});
}
catch (ex) {
alert(ex.message)
}
But this code is not working and the plugin can't find my database file(no reaction at all).
Is my way of defining database name option wrong ?Or is there another way to do this?
It is so critical for me to process spatial data in my app. So any help make this plugin work is so appreciated.
Thanks in advance.
