### ISSUE TITLE
Not working with @ionic-native/sqlite

### ISSUE THREAD

**Issue by Toterbiber** [DisyInformationssysteme/Cordova-spatialite-storage#8]
I tryed using the plugin with @ionic-native/sqlite in my angular 2 material application. Everything works fine with the normal cordova-sqlite-storage plugin, but when I remove it and add yours my create call returns null.

Is this plugin not supposed to be used with @ionic-native? Is there an alternative?

**Comment by Toterbiber** [comment]
Now I got it running somehow so I closed it.

**Comment by Cultrarius** [comment]
Hey, thanks for the update - did you figure out was caused the problem?

**Comment by Toterbiber** [comment]
Yes, I had some old stuff from the regular sqlite plugin mixed in my Android Platform Folder for some reason.
